### ISSUE TITLE
JS and Model Validations

### ISSUE THREAD

**Issue by tarellel** [kellishaver/quality-time#1]
I saw you're latest project and I'm liking it thus far.

I figured I'd those something in, in you wish to add JS and Model based validations. I understand it's a major pain getting all the rows to validate the same data. But please checkout my pull request/commit, I have setup a validator to be used on the params that are being updated.

----- 
[https://github.com/tarellel/quality-time/commit/9a09aea6c5aca24809358fc77fa0a13f4bb79f2d](https://github.com/tarellel/quality-time/commit/9a09aea6c5aca24809358fc77fa0a13f4bb79f2d)

**Comment by tarellel** [comment]
As a side note to reduce the database size and a bit of the load (not like it's a HUGE application at the moment) with using strings as the day/time activity, you may want to resort to using a integer based enum in the models.

```ruby
# DaysModel
enum moment: %w(work personal family friends sleep wasted unknown)

# The activity would be a number in the database, but in the app would be associated as moment[:work] etc.
moment [work: 1, personal: 2, family: 3, friends: 4, sleep: 5, wasted: 6, unknown: 7]
```

**Comment by tarellel** [comment]
By the way, if you need an example to ensure proper validation of the pull request here is a sample to swap `days.coffee / days.js` with.

```coffeescript
jQuery ->

  $('body').on 'click', '.time-set', (e) ->
    e.preventDefault()
    if $(this).hasClass('sleep')
      $(this).removeClass('sleep').addClass('work')
      spent_on = 'eating'
    else if $(this).hasClass('work')
      $(this).removeClass('work').addClass('personal')
      spent_on = 'fruit'
    else if $(this).hasClass('personal')
      $(this).removeClass('personal').addClass('family')
      spent_on = 'crime'
    else if $(this).hasClass('family')
      $(this).removeClass('family')
      spent_on = 'PowerRangers'
    else
      $(this).addClass('sleep')
      spent_on ='HorseRiding'

    $.ajax $('#day').data('url'),
      dataType: 'JSON',
      method: 'PATCH',
      data: {
        day: {
          "#{$(this).data('time')}": spent_on
        }
      }
```

**Comment by kellishaver** [comment]
Hey, thanks for the PR! Initially it was just a tiny thing for me to use, so I left a lot of that out, but yeah, adding validations is a very good idea.
